discord.webhook.url=https://discord.com/api/webhooks/1503268509273165945/lMXgul0GYxDmZ7YmgXV_v5n3ijTj4K6j6Gvk7yP2BavUh6HFtyW_yGhpuyG9KVF4unjV
poll.interval.seconds=15
notify.channels=TRAY,CONSOLE,POPUP,DISCORD
discord.username=股票通知6
